apiVersion: apps/v1
kind: Deployment
metadata:
  name: y42-deployment
  labels:
    app: y42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: y42
  template:
    metadata:
      labels:
        app: y42
    spec:
      containers:
      - name: y42
        image: deltacrayo/y42:latest
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: y42-service
spec:
  type: NodePort
  selector:
    app: y42
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001

